version: "3.7"
services:

  lnbits:
    hostname: lnbits
    depends_on:
      - boltz
      - mempool-api
      - lnd-3
    image: lnbitsdocker/lnbits-legend
    restart: on-failure
    user: "0:0"
    entrypoint: "sh -c 'sleep 30; poetry run lnbits'"
    environment:
      HOST: lnbits
      PORT: 5001
      DEBUG: true
      LNBITS_BACKEND_WALLET_CLASS: "LndRestWallet"
      LNBITS_DATA_FOLDER: "./data"
      LND_REST_ENDPOINT: "https://lnd-3:8081/"
      LND_REST_CERT: "./lnd/tls.cert"
      LND_REST_MACAROON: "./lnd/data/chain/bitcoin/regtest/admin.macaroon"
    ports:
      - 5001:5001
    volumes:
      - lnbits-data:/app/data
      - ./data/lnd-3:/app/lnd:uid=1000,gid=1000

  boltz:
    hostname: boltz
    depends_on:
      - lnd-2
    image: boltz/backend
    entrypoint: "sh -c 'sleep 40; /boltz-backend/bin/boltzd'"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/lnd-2:/data/lnd/
      - ./data/boltz/:/root/.boltz/
  cashu-mint:
    hostname: cashu-mint
    depends_on:
      - lnbits
    image: cashu:0.4.2
    entrypoint: "sh -c 'sleep 60; sh /app/entrypoint.sh'"
    # entrypoint: "poetry run mint --port 3338 --host 0.0.0.0"
    ports:
      - 3338:3338
    environment:
      MINT_PRIVATE_KEY: supersecretprivatekey
    volumes:
      - ./data/cashu/:/root/.cashu/
  bitcoind:
    hostname: bitcoind
    image: boltz/bitcoin-core:23.0
    command: "-regtest -fallbackfee=0.00000253 -zmqpubrawtx=tcp://0.0.0.0:29000 -zmqpubrawblock=tcp://0.0.0.0:29001 -txindex -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=lnbits -rpcpassword=lnbits"
    expose:
      - 29000
      - 29001
      - 18443
      - 18444

  clightning-1:
    hostname: clightning-1
    depends_on:
      - bitcoind
    image: boltz/c-lightning:0.12.0
    entrypoint: "sh -c 'sleep 15 && lightningd --network regtest --bind-addr=0.0.0.0:9735 --bitcoin-rpcconnect=bitcoind --bitcoin-rpcport=18443 --bitcoin-rpcuser=lnbits --bitcoin-rpcpassword=lnbits --grpc-port=11109'"
    expose:
      - 9735
    ports:
      - 11109:11109
    volumes:
      - ./data/clightning-1:/root/.lightning/

  clightning-2:
    hostname: clightning-2
    depends_on:
      - bitcoind
    image: boltz/c-lightning:0.12.0
    entrypoint: "sh -c 'sleep 15 && lightningd --network regtest --bind-addr=0.0.0.0:9735 --bitcoin-rpcconnect=bitcoind --bitcoin-rpcport=18443 --bitcoin-rpcuser=lnbits --bitcoin-rpcpassword=lnbits'"
    expose:
      - 9735
    volumes:
      - ./data/clightning-2:/root/.lightning/

  lnd-1:
    hostname: lnd-1
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.0-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd-1:9735 --rpclisten=lnd-1:10009 --restlisten=lnd-1:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=lnbits --bitcoind.rpcpass=lnbits --noseedbackup --protocol.wumbo-channels'"
    ports:
      - 8081:8081
      - 10009:10009
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-1:/root/.lnd/

  lnd-2:
    hostname: lnd-2
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.0-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd-2:9735 --rpclisten=lnd-2:10009 --restlisten=lnd-2:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=lnbits --bitcoind.rpcpass=lnbits --noseedbackup --protocol.wumbo-channels'"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-2:/root/.lnd/

  lnd-3:
    hostname: lnd-3
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.0-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd-3:9735 --rpclisten=lnd-3:10009 --restlisten=lnd-3:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=lnbits --bitcoind.rpcpass=lnbits --noseedbackup --protocol.wumbo-channels'"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-3:/root/.lnd/

  electrs:
    depends_on:
      - bitcoind
    hostname: electrs
    image: getumbrel/electrs:latest
    environment:
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs:50001"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:18443"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:18444"
    entrypoint: "sh -c 'sleep 15 && electrs'"
    ports:
      - 50001:50001
    volumes:
      - ./data/electrs/:/data/.electrs/

  mempool-web:
    restart: on-failure
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    image: mempool/frontend:latest
    ports:
      - 8080:8080

  mempool-api:
    depends_on:
      - electrs
      - mempool-db
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: electrs
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "lnbits"
      CORE_RPC_PASSWORD: "lnbits"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    restart: on-failure

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8

volumes:
  lnbits-data:
